- ssd.py
- test_ssd.py
> feature: ssd write

- shell.py
- test_shell.py
shell에서 help 입력 시, 프로그램 사용법 출력 될 수 있도록 기능 추가 하였습니다.
> shell에서 help 입력 시, 프로그램 사용법 출력 될 수 있도록 기능 추가 하였습니다.

- shell.py
- test_shell.py
shell 클래스에서 ssd의 write를 사용하여 모든 주소에 write하는 기능 추가했습니다.
> [feat] shell write_all function 추가

- shell.py
- ssd.py
- test_shell.py
To fix test_ssd error,
add default value for ssd_nand and ssd_output
> [fix] fix ssd init

- test_ssd.py
test code refactoring하여 PR요청합니다.
> [refact] ssd의 고정 값 변수 제거 및 코드 스타일 정리

- shell.py
- ssd.py
- test_ssd.py
fix variable
address -> lba
자동으로 close 해주는 with open 으로 변경
> [refactoring] fix variable and use with open function.

- shell.py
- test_shell.py
To ensure data consistency, run ssd_reset
> [fix] add _ssd_reset

- ssd.py
> Refac: apply sinlgton ssd class

- ssd.py
write 함수 value 파라미터 힌트 명시했습니다.
> Add type hints to ssd write function parameters

- shell.py
- test_shell.py
To print "[Write] Done", fix write function
> [fix] write function

- test_shell.py
> refac: test code refatoring

- shell.py
change read function to use subprocess
$ python shell.py 
Shell> read 0
[Read] LBA 00 : 0x00000000
> [refact] change read function

- shell.py
To remove "enter", add strip() function
> [refact] fix _read

- shell.py
- test_shell.py
partialLBAwrite의 read, write 수정 및 test 코드 수정했습니다.
> [fix] read and write in partialLBAwrite

- ssd.py
add write methods
add type hints
> refac: add 'write_nand' and 'write_output' for write ssd_.txt file with others

- test_shell.py
[Fix] Full Read Call Test 수정 하였습니다.
TEST 진행 시, PASS 확인 하였습니다.
> [fix] 함수 이름 변경으로 full_read_call Test 수정

- test_shell.py
test_cmd_fullread are duplicates test_full_read_valid
> [refact] remove duplicated test function

- shell.py
- test_shell.py
shell.py와 test_shell.py에서 ssd에 의존하는 부분 삭제했습니다.
> remove import ssd in shell.py and test_shell.py

- shell.py
> [refact] remove duplicated import

- shell.py
value가 16진수로 들어오는지 확인
ssd_output.txt 에 write 시 ""인지로 true false 판단
> [fix] shell write 

- .gitignore
- logger.py
- shell.py
add initail logger 추가입니다.
Shell> read 0
[Read] LBA 00 : 0x00000000
출력
[25.07.16 08:27] Shell.read()           : [Read] LBA 00 : 0x00000000
> [feat] add logger

- shell.py
1. 확률적으로 이전과 중복된 값으로 테스트 할 수 있던 1_ 테스트 스크립트 수정
> [fix] 이전과 중복되지 않은 랜덤 값 설정 1_ script

- shell.py
- test_shell.py
> [fix] add erase and erase_range in help

- ssd.py
- test_ssd.py
ssd erase 기능 구현 및 test code 추가하여 PR요청드립니다.
- 해당 lba부터 size만큼 0x00000000으로 write하는 기능
- 명세서에 써있는 error 상황에 따른 error 처리
> [feature] ssd erase 기능 구현 및 test code 추가

- test_command_buffer.py
add command buffer flush test base
> add test for command_buffer

- buffer.py
> [feature] Buffer 클래스 및 인터페이스 추가

- shell.py
invalid 내 신규 test 내용 추가 하였습니다.
> [fix] invalid 내 신규 test 내용 추가

- shell.py
> [fix] checkInvalid

- shell.py
[fix] shell main 함수 return 받아 종료 되도록 변경하였습니다.
> [fix] shell main 함수 return 받아 종료 되도록 변경

- buffer.py
- shell.py
- test_shell.py
buffer class에 erase 추가
buffer class 동작 가정하고 shell에 buffer 구현
main함수 변경으로 test_shell test 깨지는 에러 수정
> add erase in buffer class; add buffer in shell; fix test_shell

- buffer.py
- test_buffer.py
buffer read, write 함수 구현 및 test code 추가하여 PR올립니다.
- read는 버퍼를 순회하면서 해당 LBA에 내용이 있는지 판단하고, 있다면 결과를 반환하는 함수
- write는 1~5까지 순회하면서 empty인 버퍼에 write하는 함수
- 버퍼에 write하고 read하여 기대하는 값과 같은지 판단하는 test 함수
> [feature] buffer read, write 함수 구현 및 test code 추가

- test_shell.py
erase_range , _write mock 작성
call로 정상 콜 되었는지 확인 및 정상 인자 들어왔는지 확인
loop 1번 돌려 반복적으로 잘 들어가는지 확인
> [test] erase_and_write_aging 구현

- test_command_buffer.py
add buffer test in 명세서, refactoring
> add buffer test

- shell.py
4_erase_and_write_aging  try catch로 PASS FAIL 설정 및 main 실행 추가
> [fix] erase_and_write_aging try catch로 PASS FAIL 설정 및 main 실행 추가

- buffer.py
- ssd.py
- test_buffer.py
buffer에 같은 LBA에 write가 들어왔을 경우 대응하는 함수 추가
> [feature] buffer Write cmd가 기존 buffer에 존재하는 cmd와 겹칠때 합치는 기능 추가

- logger.py
- shell.py
it print startshell not class.method. So fix it.
error ->  [25.07.16 16:30] UnknownClass.startShell()
> [fix] fix print error

- test_shell.py
runner unittest call_once 추가 했습니다.
> [add] runner unittest call_once 추가

- test_ssd.py
cli를 통해서 실행되는 ssd read, write, erase 명령과 ssd_output.txt 파일 읽기를 함수로 추출했습니다.
> [refactor] 중복 로직 함수로 추출

- test_shell.py
> [refact] Remove duplicate tests

- buffer.py
E가 추가됐을 때 범위가 겹치는 W를 버퍼에서 제거하는 기능을 추가했습니다.
> [feature] E 추가됐을 때 buffer에서 겹치는 W제거

- buffer.py
기존 size가 1인 erase와 새로운 write가 겹칠 경우 처리 코드 추가하여 PR 올립니다.
> [feature] 기존 size가 1인 erase와 새로운 write가 겹칠 경우 처리 코드 추가

- buffer.py
- ssd.py
> [refact] ssd flush

- test_buffer.py
> fix: test logic fix

- buffer.py
buffer에 존재하는 erase에 대해 lba 범위로 찾게 수정하였습니다.
> [fix] buffer read에서 erase에 대한 logic 수정

- shell.py
runner에 4번 textScript 실행하도록 추가 했습니다.
> [add] runner에 4번 textScript 실행하도록 추가

- shell.py
- ssd.py
- test_shell.py
> [feature] add flush in shell

- shell.py
- 4번 테스트스크립트 실행 시 erase range done이 계속해서 실행되는 오류 수정
- erase_range 기능을 _erase_range로 분리
> [fix] 4번 테스트 스크립트에서 erase_range 호출 시 잘못된 프린트 제거

- buffer.py
get_sorted_buffer_file_list에서 불필요한 함수 제거하고 내장 함수 사용하여 리팩토링 했습니다.
> [refact] get_sorted_buffer_file_list

- .flake8
> [feat] add flake8

- ssd.py
> refac: ssd.py refactoring (pep8)

- test_buffer.py
> refac: apply pep8 and clean code

- command_shell.py
pep8 적용하여 class 사이의 공백은 두 줄로 수정했습니다.
> refac: apply pep8

- shell.py
- test_shell.py
add log_and_print for shell method and fix test_shell
> [refactoring] add log_and_print

- buffer.py
buffer.py flake8 기반으로 refactoring하여 PR요청합니다.
> [refact] flake8 기반으로 buffer.py refactoring

- test_shell.py
shell_test에 주석 추가 및 목적에 맞도록 test 수정 했습니다.
> [Refactor] test add comment

- buffer.py
> [refact] join_erase_command

- shell.py
> refac: apply pep 8

- test_shell.py
[refact] test_runner_call shell.main() > shell.command_main() 으로 변경
> [refact] test_runner_call shell.main() > shell.command_main() 으로 변경

- buffer.py
> [refact] buffer write

- shell.py
fix log_and_print to use return value
> [fix] fix log_and_print

- buffer.py
- test_buffer.py
delete_write_command 리팩토링했습니다.
> [refact] delete_write_command

- command_factory.py
- shell.py
[refact] flake8 and delete find_command method
> [refact] flake8 and delete find_command method

- ssd.py
- test_ssd.py
> [refact] replace magic numbers with constants in ssd

- shell.py
- test_shell.py
> [refact] replace magic numbers with constants
